
#A few general things to note:
#Any invalid entries will result in a log warning, but will just be skipped, and working entries will work.
#Most entries will utilize a block, item or enchantment id, which needs to be in the modid:blockid, modid:itemid or modid:enchantmentid format, respectively. "minecraft:" is not optional.
#Alternatively, you can use "any" instead of a block or item id to have the setting be applied to all blocks/items.
#Entries are read from left to right, so you'd better put "any"-entries to the left.
#NBT is currently not supported in any way.
[logging]
	#Whether to log successful operations or not.
	log_successful = true
	#Whether to log failed operations or not.
	log_errors = true

[item_groups]
	#Define new item groups. Format is "id;icon", with icon being an item id. Will run before the below stuff, allowing you to use these groups below. Note that you need to set a translation using a resource pack, otherwise an itemGroup.<id> translation key will appear. Also, do not use "none" as a name, as this is the key used to remove an item from any group.
	item_group = []
	#Removes item groups that have no items, including empty ones created by this mod. Runs after the below stuff, clearing up any empty groups left from moving all items out of them.
	remove_empty_item_groups = true

#Dumps all corresponding values, each with their changeable properties, into the logs.
[dump]
	#Dump blocks BEFORE applying the changes.
	dump_blocks = false
	#Dump blocks AFTER applying the changes.
	dump_blocks_after = false
	#Dump blocks BEFORE applying the changes. Only dumps non-default values. Does nothing if dump_blocks is set to true.
	dump_blocks_non_default = false
	#Dump blocks AFTER applying the changes. Only dumps non-default values. Does nothing if dump_blocks_after is set to true.
	dump_blocks_after_non_default = false
	#Dump items BEFORE applying the changes. Due to technical reasons, repair materials cannot be dumped.
	dump_items = false
	#Dump items AFTER applying the changes. Due to technical reasons, repair materials cannot be dumped.
	dump_items_after = false
	#Dump items BEFORE applying the changes. Due to technical reasons, repair materials cannot be dumped. Only dumps non-default values. Does nothing if dump_items is set to true.
	dump_items_non_default = false
	#Dump items AFTER applying the changes. Due to technical reasons, repair materials cannot be dumped. Only dumps non-default values. Does nothing if dump_items is set to true.
	dump_items_after_non_default = false
	#Dump enchantments BEFORE applying the changes.
	dump_enchantments = false
	#Dump enchantments AFTER applying the changes.
	dump_enchantments_after = false
	#Dump item groups BEFORE applying the changes.
	dump_groups = false
	#Dump item groups AFTER applying the changes.
	dump_groups_after = false
	#The default enchantability of items. Change this if you have a mod installed that makes every item enchantable (and thus have a different enchantability). If you're unsure, leave this unchanged and run the item dumping. You will see if you need to change it or not.
	#Range: > -2147483648
	default_enchantability = 0

#Settings related to blocks. Format is "blockid;value", unless stated otherwise.
[blocks]
	#How long the block takes to break. 0.5 is dirt, 1.5 is stone, 50 is obsidian. -1 makes the block unbreakable. Not recommended for blocks with blockstate-dependent hardness that may be added by other mods. Default value: 0
	hardness = []
	#How blast-resistant the block is. 0.5 is dirt, 6 is stone and cobblestone, 1200 is obsidian. 3600000 or more makes the block unbreakable. Default value: 0
	resistance = []
	#The block's harvest level. -1 is any harvest level. Default value: -1
	harvest_level = []
	#The block's harvest tool. Must be one of axe, hoe, pickaxe, shovel or none.
	harvest_tool = []
	#Whether you need a corresponding tool, as set by the harvest tool, at least of the harvest level to get block drops (e.g. stone) or if the harvest tool type only speeds up the breaking speed (e.g. dirt). Default value: false
	requires_tool = []
	#The light level emitted by this block. Not recommended for blocks with blockstate-dependant light level (e. g. furnaces). Default value: 0
	light_level = []
	#How slippery the block is. Default value: 0.6
	slipperiness = []
	#Accelerates (if > 1) or slows down (if between 0 and 1) entities that walk upon this block. Default value: 1
	speed_factor = []
	#Allows entities on this block to jump higher (if > 1) or lower (if between 0 and 1). Default value: 1
	jump_factor = []
	#The sound type the block has. Currently, only vanilla sound types are supported. Default value: stone. Vanilla sound types are:
	#wood, ground, plant, lily_pads, stone, metal, glass, cloth, sand, snow, ladder, anvil, slime, honey, wet_grass, coral, bamboo, bamboo_sapling, scaffolding, sweet_berry_bush, crop, stem, vine, nether_wart, lantern, hyphae, nylium, fungus, root, shroomlight, nether_vine, nether_vine_lower_pitch, soul_sand, soul_soil, basalt, wart, netherrack, nether_brick, nether_sprout, nether_ore, bone, netherite, ancient_debris, lodestone, chain, nether_gold, gilded_blackstone
	sound_type = []

#Settings related to items. Format is "item;value", unless stated otherwise.
[items]
	#The max durability an item has. Can only be set on damageable items. Default value: 0
	max_damage = []
	#The max stack size an item has. Cannot be set on damageable items. Default value: 64 (1 for damageable items)
	max_stack_size = ["minecraft:ender_pearl"]
	#The item group (= creative tab) of an item. Use "none" to remove the item from any item group. Default value: none
	group = []
	#Whether the item should have the fire and lava shielding properties of netherite or not. Default value: false
	is_immune_to_fire = []
	#Sets the item rarity (aka text color). Must be one of common (white), uncommon (yellow), rare (aqua) and epic (light purple). Default value: common
	rarity = []
	#Sets the enchantability of the item. Default value: 0
	enchantability = []
	#Sets the repair material of the item. Tags (e.g. #minecraft:planks) are also allowed.
	repair_material = []

	#Settings related to armor. Only armor items (excluding the elytra) can be affected, anything else will be skipped.
	[items.armor]
		#Sets the armor value.
		armor = []
		#Sets the armor toughness value. Default value: 0
		toughness = []
		#Sets the knockback resistance. Default value: 0
		knockback_resistance = []

	#Settings related to tools. Only tool, sword and trident items can be affected, anything else will be skipped.
	[items.tools]
		#Sets the attack damage.
		attack_damage = []
		#Sets the attack speed.
		attack_speed = []
		#Sets the tool harvest level. Does not work for swords and tridents.
		harvest_level = []
		#Sets the efficiency. Does not work for swords and tridents.
		efficiency = []

#Settings related to enchantments. Format is "enchantment;value", unless stated otherwise.
[enchantments]
	#The enchantment rarity of this enchantment. Must be one of common (10), uncommon (5), rare (2) and very_rare (1).
	rarity = []
	#The item group this enchantment type's enchanted books are in. As soon as you add one for an item group, you need to re-add every enchantment type for that group as well.
	group = []
	#Remove enchantment books from creative tabs. Runs before group, so re-adding is possible.
	remove_item_groups = false

